[build]
  command = "npm run build"
  export = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/cryptocurrencies/[symbol]"
  to = "/"
  status = 301
  force = false
